CREATE TABLE `kader_detail` (
  `id` int NOT NULL,
  `user_id` int DEFAULT NULL,
  `kader_since` int DEFAULT NULL,
  `nik` varchar(20) DEFAULT NULL,
  `ktp_address` varchar(255) DEFAULT NULL,
  `residence_address` varchar(255) DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `gender` enum('Laki-laki','Perempuan') DEFAULT NULL,
  `education` varchar(50) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `health_insurance` varchar(10) DEFAULT NULL,
  `bank_account` varchar(50) DEFAULT NULL,
  `posyandu_area` varchar(100) DEFAULT NULL,
  `posyandu_name` varchar(100) DEFAULT NULL,
  `training` varchar(500) DEFAULT NULL,
  `photo` varchar(500) DEFAULT NULL,
  `status` enum('Aktif','Tidak Aktif') DEFAULT 'Aktif',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `kader_detail_ibfk_1` FOREIGN KEY (`id`) REFERENCES `users` (`id`),
  CONSTRAINT `kader_detail_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;